# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"0\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\"1\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\xab\x01\n\x10HeartbeatRequest\x12\x10\n\x08leaderId\x18\x08 \x01(\x05\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x15\n\rleaseDuration\x18\x02 \x01(\x01\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cprevLogIndex\x18\x05 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x06 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x07 \x01(\x05\"2\n\x11HeartbeatResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\'\n\x14\x43lientRequestMessage\x12\x0f\n\x07request\x18\x01 \x01(\t\"P\n\x15\x43lientResponseMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rleaderAddress\x18\x03 \x01(\x05\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t2\xca\x01\n\x04Raft\x12\x36\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\"\x00\x12>\n\tHeartbeat\x12\x16.raft.HeartbeatRequest\x1a\x17.raft.HeartbeatResponse\"\x00\x12J\n\rClientRequest\x12\x1a.raft.ClientRequestMessage\x1a\x1b.raft.ClientResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=68
  _globals['_VOTERESPONSE']._serialized_start=70
  _globals['_VOTERESPONSE']._serialized_end=119
  _globals['_HEARTBEATREQUEST']._serialized_start=122
  _globals['_HEARTBEATREQUEST']._serialized_end=293
  _globals['_HEARTBEATRESPONSE']._serialized_start=295
  _globals['_HEARTBEATRESPONSE']._serialized_end=345
  _globals['_CLIENTREQUESTMESSAGE']._serialized_start=347
  _globals['_CLIENTREQUESTMESSAGE']._serialized_end=386
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_start=388
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_end=468
  _globals['_LOGENTRY']._serialized_start=470
  _globals['_LOGENTRY']._serialized_end=511
  _globals['_RAFT']._serialized_start=514
  _globals['_RAFT']._serialized_end=716
# @@protoc_insertion_point(module_scope)
